DROP TABLE IF EXISTS CITIES CASCADE;

CREATE TABLE CITIES {
    id SERIAL PRIMARY KEY NOT NULL,
    CITY_NAME varchar(60),
}

INSERT INTO CITIES (CITY_NAME) VALUES
    ('Rochester'),
    ('Atlanta'),
    ('Paris')
    ('Tokyo')